Task: "go2seesaw"
env_path: "./mqe/envs/wrappers/go2_seesaw_wrapper_source.py"
num_reward_samples: 3
num_reward_feedback_samples: 2 
iter_per_task: 20000000
line_num: 259
eureka:
  num_iterations: 3
  num_candidates: 3
  intermediate_eval_seeds: [0]
  final_eval_seeds: [0, 1, 2, 3, 4]
  objective_terms:
    - tag: "Eval/success_rate"
      stat: "last"
      mode: "max"
      weight: 1.0
  tie_breaker_terms:
    - tag: "Eval/agent_1_height"
      stat: "mean"
      mode: "max"
      weight: 1.0
    - tag: "Eval/fall"
      stat: "mean"
      mode: "min"
      weight: 1.0
eureka_debug:
  num_iterations: 1
  num_candidates: 1
  training_iter: 1000
  intermediate_eval_seeds: [0]
  final_eval_seeds: []
